"""Interactive setup wizard — guides user through first-time configuration.

Creates ~/.config/comar/config.toml with server address, token, vault path,
and vault path.
"""

import logging
import os
from pathlib import Path

import click

from comar.config import CONFIG_DIR, CONFIG_FILE

logger = logging.getLogger(__name__)

# The vault marker — this subfolder only exists inside the comar vault
_VAULT_MARKER = Path("vault") / "COG Personal"


def run_setup_noninteractive(
    user: str,
    token: str,
    server_url: str,
    vault_path: str | None = None,
) -> None:
    """Non-interactive setup for bootstrap / automated installs.

    Auto-detects vault path if not provided. Falls back to plain HTTP
    if no CA cert is available (LAN-only — fine for V3).
    """
    click.echo(f"\n  comar setup (non-interactive, user={user})\n")

    # Resolve vault path
    if vault_path:
        vp = Path(vault_path).expanduser().resolve()
    else:
        vp = _detect_vault_path()
        if vp:
            click.echo(f"  Auto-detected vault: {vp}")
        else:
            vp = Path.home() / "Desktop" / "Code" / "comar" / "vault"
            click.echo(f"  No vault found, defaulting to: {vp}")

    ca_cert_path = CONFIG_DIR / "ca.pem"

    # Test connection
    click.echo("  Testing server connection...", nl=False)
    ok, msg = _test_connection(server_url, ca_cert_path, token, user)
    if ok:
        click.echo(f" ✓ ({msg})")
    else:
        click.echo(f" ✗ ({msg})")
        click.echo("  Continuing anyway — will retry on daemon start")

    # Write config
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    config_content = f"""# Comar client configuration
# Generated by `comar setup --token ... --user ... --server ...`

user = "{user}"
mcp_port = 9400
auto_update = true

[server]
urls = ["{server_url}"]
ca_cert = "{ca_cert_path}"
token = "{token}"

[vault]
path = "{vp}"
"""
    CONFIG_FILE.write_text(config_content)
    os.chmod(CONFIG_FILE, 0o600)  # contains the bearer token — owner read/write only
    click.echo(f"\n  Config saved to {CONFIG_FILE} ✓")
    click.echo("  Run `comar install` to start the daemon.\n")


def run_setup():
    """Interactive setup wizard."""
    click.echo("\n  comar setup\n")

    # 1. User name
    user = click.prompt("  What's your name?", type=click.Choice(["alex", "sam"], case_sensitive=False))

    # 2. Vault path
    detected = _detect_vault_path()
    if detected:
        vault_path = click.prompt("  Vault path?", default=str(detected))
    else:
        vault_path = click.prompt("  Vault path?")
    vault_path = Path(vault_path).expanduser().resolve()

    if not vault_path.is_dir():
        click.echo(f"  Warning: {vault_path} does not exist yet")

    # 3. Server address
    server_url = click.prompt("  Server address?", default="localhost:9443")

    # 4. Client token
    token = click.prompt("  Client token", hide_input=True)

    # 5. CA certificate
    ca_cert_path = CONFIG_DIR / "ca.pem"
    if ca_cert_path.is_file():
        click.echo(f"  CA cert: {ca_cert_path} ✓")
    else:
        ca_cert_input = click.prompt(
            "  Path to CA certificate (ca.crt from server)",
            default="",
        )
        if ca_cert_input:
            src = Path(ca_cert_input).expanduser()
            if src.is_file():
                CONFIG_DIR.mkdir(parents=True, exist_ok=True)
                ca_cert_path.write_bytes(src.read_bytes())
                os.chmod(ca_cert_path, 0o600)
                click.echo(f"  CA cert copied to {ca_cert_path} ✓")
            else:
                click.echo(f"  Warning: {src} not found — HTTP will fall back to plain (LAN-only)")

    # 6. Test connection
    click.echo("\n  Testing server connection...", nl=False)
    ok, msg = _test_connection(server_url, ca_cert_path, token, user)
    if ok:
        click.echo(f" ✓ ({msg})")
    else:
        click.echo(f" ✗ ({msg})")
        if not click.confirm("  Continue anyway?", default=False):
            return

    # 7. Test Reminders access
    click.echo("  Testing Reminders access...", nl=False)
    if _test_reminders():
        click.echo(" ✓")
    else:
        click.echo(" ✗ (osascript failed — grant Reminders access in System Settings)")

    # 8. Write config
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    config_content = f"""# Comar client configuration
# Generated by `comar setup`

user = "{user}"
mcp_port = 9400

[server]
urls = ["{server_url}"]
ca_cert = "{ca_cert_path}"
token = "{token}"

[vault]
path = "{vault_path}"
"""

    CONFIG_FILE.write_text(config_content)
    os.chmod(CONFIG_FILE, 0o600)  # contains the bearer token — owner read/write only
    click.echo(f"\n  Config saved to {CONFIG_FILE} ✓")
    click.echo("\n  Run `comar install` to start the daemon as a service.")
    click.echo("  Or `comar daemon` to run in the foreground.\n")


def _detect_vault_path() -> Path | None:
    """Try to auto-detect the vault directory.

    Walks the home directory (up to 7 levels) looking for vault/COG Personal.
    Prunes hidden dirs and known-heavy directories to stay fast.
    """
    import os

    home = str(Path.home())
    _PRUNE = {".", "node_modules", "Library", "__pycache__", ".Trash", "venv", "site-packages"}
    max_depth = 7

    for dirpath, dirnames, _ in os.walk(home):
        # Prune hidden and heavy directories
        dirnames[:] = [
            d for d in dirnames
            if not d.startswith(".") and d not in _PRUNE
        ]
        # Enforce max depth
        rel_depth = dirpath[len(home):].count(os.sep)
        if rel_depth >= max_depth:
            dirnames.clear()
            continue
        # Check for the marker
        candidate = Path(dirpath) / _VAULT_MARKER
        if candidate.is_dir():
            return candidate
    return None


def _test_connection(url: str, ca_cert: Path, token: str, user: str) -> tuple[bool, str]:
    """Test HTTP connection to the server. `url` is the V3 base URL."""
    try:
        import httpx

        base = url.rstrip("/")
        if not base.startswith(("http://", "https://")):
            base = f"http://{base}"

        verify: object = True
        if ca_cert and ca_cert.is_file():
            verify = str(ca_cert)

        with httpx.Client(
            base_url=base,
            headers={"Authorization": f"Bearer {token}"},
            verify=verify,
            timeout=10.0,
        ) as client:
            resp = client.get("/api/v1/heartbeat", params={"client_version": "setup"})
            resp.raise_for_status()
            tools_resp = client.get("/api/v1/tools")
            tools_resp.raise_for_status()
            return True, f"{len(tools_resp.json())} tools available"
    except Exception as e:  # noqa: BLE001
        return False, str(e)


def _test_reminders() -> bool:
    """Test Apple Reminders access via osascript."""
    import subprocess
    try:
        r = subprocess.run(
            ["osascript", "-e", 'tell application "Reminders" to name of every list'],
            capture_output=True, text=True, timeout=10,
        )
        return r.returncode == 0
    except Exception:
        return False
