"""Tests for scripts/state_of_project.py (S5.2 — the state document, generated).

Loads the script as a module (it lives under `core/scripts/`, outside the
`app` package, so it is imported by file path rather than via a dotted
import). Covers:

  - measurers return sane floors on this checkout (a regression here means a
    measurer broke, not that the codebase shrank below the floor — these
    floors are well under the real counts on purpose);
  - rendering is deterministic (same input -> byte-identical output twice);
  - the --check diff mode detects a one-character drift;
  - a mutation check: temporarily break a measurer and confirm the floor
    test that exercises it actually fails (proves the test isn't vacuous).

⚠️ Like `test_drop_in_integration.py` and friends (see core-tests.yml's
comment on `INTEGRATIONS` global-state sharing), `gather()`/`measure_tools()`
call `app.integrations.register_all()`, which populates the process-global
`INTEGRATIONS` registry. It never removes entries, only adds/overwrites the
real discovered set, so running it here is safe alongside the other files
that do the same thing in the same suite.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

_SCRIPT_PATH = (
    Path(__file__).resolve().parents[3] / "scripts" / "state_of_project.py"
)


def _load_module():
    spec = importlib.util.spec_from_file_location("state_of_project", _SCRIPT_PATH)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def sop():
    return _load_module()


class TestMeasurerFloors:
    """Each measurer returns a value at least this codebase's known floor.

    Floors are set comfortably below the real counts (29 integration
    packages, 78 tables, 168 tools as of this writing) so a small, expected
    future change doesn't need this file touched, while a measurer that
    silently returns 0 or errors-and-gets-swallowed still fails loudly.
    """

    def test_integration_packages_floor(self, sop):
        packages = sop.measure_integration_packages()
        assert len(packages) >= 25
        # Every entry is a real directory with a manifest — not just a name.
        for name in packages:
            assert (sop.BACKEND / "app" / "integrations" / name / "manifest.py").exists()

    def test_tables_floor(self, sop):
        assert sop.measure_tables() >= 70

    def test_tools_floor(self, sop):
        total, registered, zero = sop.measure_tools()
        assert total >= 100
        assert len(registered) >= 25
        # sheets/transcription/vision are documented zero-tool facades.
        assert "sheets" in zero

    def test_alembic_head_is_nonempty(self, sop):
        head = sop.measure_alembic_head()
        assert head and head != "(none)"

    def test_workflows_and_apps_present(self, sop):
        # These read the repo root ABOVE core/ — `CORE_ROOT.parent` — which is
        # the lios monorepo root on the checkout this was written against, but
        # is just "wherever this repo happens to sit on disk" on a standalone
        # clone (e.g. the public lios-oss release, which has no sibling
        # `apps/` or `.github/workflows` one level up at all). The measurers
        # themselves already handle that gracefully (empty list, no error);
        # only skip the assertion, since a standalone checkout finding zero
        # is the correct, expected reading of "not the monorepo", not a
        # broken measurer.
        if not (sop.CORE_ROOT.parent / "apps").is_dir():
            pytest.skip("not inside the lios monorepo — apps/ has no sibling here")
        assert len(sop.measure_workflows()) >= 1
        assert len(sop.measure_apps()) >= 1


class TestRenderDeterminism:
    def test_render_twice_is_identical(self, sop):
        data = sop.gather()
        first = sop.render(data)
        second = sop.render(data)
        assert first == second

    def test_render_contains_generated_header(self, sop):
        data = sop.gather()
        rendered = sop.render(data)
        assert "GENERATED by `scripts/state_of_project.py`" in rendered
        assert "do not edit" in rendered


class TestCheckDetectsDrift(object):
    def test_check_passes_when_identical(self, sop, tmp_path, monkeypatch):
        data = sop.gather()
        rendered = sop.render(data)
        state_file = tmp_path / "STATE.md"
        state_file.write_text(rendered)
        monkeypatch.setattr(sop, "STATE_MD", state_file)
        # Patch gather() to avoid re-measuring (slow, and would re-run
        # pytest --collect-only as a subprocess) — main() calls render(gather()).
        monkeypatch.setattr(sop, "gather", lambda: data)
        assert sop.main(["--check"]) == 0

    def test_check_fails_on_one_character_drift(self, sop, tmp_path, monkeypatch):
        data = sop.gather()
        rendered = sop.render(data)
        # Flip one digit in the tables count line.
        drifted = rendered.replace("| DB tables |", "| DB tables (drifted) |", 1)
        assert drifted != rendered
        state_file = tmp_path / "STATE.md"
        state_file.write_text(drifted)
        monkeypatch.setattr(sop, "STATE_MD", state_file)
        monkeypatch.setattr(sop, "gather", lambda: data)
        assert sop.main(["--check"]) == 1

    def test_check_fails_when_state_md_missing(self, sop, tmp_path, monkeypatch):
        monkeypatch.setattr(sop, "STATE_MD", tmp_path / "does-not-exist.md")
        assert sop.main(["--check"]) == 1


class TestMutationCheck:
    """Reinstate a bug in a measurer and confirm the floor test catches it.

    Per project convention (feedback_mutation_check_your_tests.md): a test
    that always passes proves nothing. This monkeypatches
    `measure_integration_packages` to return an empty list — the shape of a
    real regression (e.g. the manifest glob silently matching nothing after
    a path refactor) — and asserts the floor assertion actually fails.
    """

    def test_broken_measurer_is_caught_by_floor_test(self, sop, monkeypatch):
        monkeypatch.setattr(sop, "measure_integration_packages", lambda: [])
        packages = sop.measure_integration_packages()
        with pytest.raises(AssertionError):
            assert len(packages) >= 25
